### ISSUE TITLE
Builder UI is not showing the latest package correctly for non-Linux packages

### ISSUE THREAD

**Issue by chefsalim** [habitat-sh/builder#825] opened 2018-12-05 23:03 UTC
Non-Linux packages are not showing any information for the latest package on the main package page, as well as the sidebar.  The UI should query latest for all supported platforms, and show the information appropriately.

**Comment by dmccown** [comment] 2018-12-06 19:56
Duplicate of #390. We'll close #390.

**Comment by apriofrost** [comment] 2018-12-14 01:51
See a live [example](https://bldr.habitat.sh/#/pkgs/core/hab-sup/latest) for the issue.

Proposed UX design to resolve the issue: 
- Add a 'view switcher' component in `package manifest` container (also a new component) 
- Display all the release numbers and its platform icons under `latest stable` in the right side column
- View [mockup](https://chef.invisionapp.com/share/UCPLOB48AVM#/336735697_package_Detail_) and [design spec](https://chef.invisionapp.com/share/UCPLOB48AVM#/336979004_package_Detail_-_View_Switcher_-_Specs)

@mgamini I've invited you to the InVision project so you can see additional specs in the[ inspec tab](https://chef.invisionapp.com/d/main#/console/16240553/336735697/inspect) if you need.

**Comment by apriofrost** [comment] 2019-08-05 19:43
Duplicate of #1098

**Closed by apriofrost** 2019-08-05 19:43 UTC
Labels: A-builder, C-bug, V-bldr, V-front-end
