### ISSUE TITLE
Add ability to add custom channels to the UI

### ISSUE THREAD

**Issue by ryankeairns** [habitat-sh/builder#447] opened 2018-05-29 21:17 UTC
As a user, I want to be able to add/remove all channels in the UI not just _stable_, so that I can move my artifact through all my environments.

**Comment by chefsalim** [comment] 2018-09-26 23:51
Duplicate of https://github.com/habitat-sh/builder/issues/425

**Closed by chefsalim** 2018-09-26 23:51 UTC
Labels: A-builder, V-front-end
