### ISSUE TITLE
Unable to promote or delete core/tlog package

### ISSUE THREAD

**Issue by jasonwbarnett** [habitat-sh/builder#1102] opened 2019-06-19 13:05 UTC
### `hab` CLI version

0.82.0/20190605214029

### Platform Details

Mac OS

### Scenario:

As a user I want to promote my package to stable channel and delete bad packages.

### Steps to Reproduce:

1. build core/tlog plan
   - `hab pkg build tlog`
1. upload hart
   - `hab pkg upload results/jasonwbarnett-tlog-6-20190619123455-x86_64-linux.hart`
1. promote to stable
   - `hab pkg promote jasonwbarnett/tlog/6/20190619123455 stable`

### Expected Result:

I expect the promoted package to be available in habitat builder.

### Actual Result:

No packages are listed in latest tab on builder and I am unable to delete the package.

This seems to specifically be plaguing the core/tlog plan.

### More details...

1. Promoted package does not appear in latest page on builder

	```
	$ hab pkg promote jasonwbarnett/tlog/6/20190619123455 stable
	» Promoting jasonwbarnett/tlog/6/20190619123455 (x86_64-linux) to channel 'stable'
	✓ Promoted jasonwbarnett/tlog/6/20190619123455 (x86_64-linux)
	```

	Even though the above succeeded, when you check the builder, there is [no packages listed in "latest"](https://bldr.habitat.sh/#/pkgs/jasonwbarnett/tlog/latest) tab. This problem is also effecting [core/tlog](https://bldr.habitat.sh/#/pkgs/core/tlog/latest).

2. Unable to delete these packages on builder:

	```
	$ hab pkg search jasonwbarnett
	jasonwbarnett/tlog/6/20190617151639
	jasonwbarnett/tlog/6/20190619123119
	jasonwbarnett/tlog/6/20190619123455
	
	$ hab pkg search jasonwbarnett | xargs -I{} hab pkg delete {}
	» Deleting jasonwbarnett/tlog/6/20190617151639 (x86_64-linux) from Builder
	Failed to delete 'jasonwbarnett/tlog/6/20190617151639': APIError(UnprocessableEntity, "")
	✗✗✗
	✗✗✗ [422 Unprocessable Entity]
	✗✗✗
	» Deleting jasonwbarnett/tlog/6/20190619123119 (x86_64-linux) from Builder
	Failed to delete 'jasonwbarnett/tlog/6/20190619123119': APIError(UnprocessableEntity, "")
	✗✗✗
	✗✗✗ [422 Unprocessable Entity]
	✗✗✗
	» Deleting jasonwbarnett/tlog/6/20190619123455 (x86_64-linux) from Builder
	Failed to delete 'jasonwbarnett/tlog/6/20190619123455': APIError(UnprocessableEntity, "")
	✗✗✗
	✗✗✗ [422 Unprocessable Entity]
	✗✗✗
	```

**Comment by jasonwbarnett** [comment] 2019-06-19 21:25
@smacfarlane based on feedback in https://github.com/habitat-sh/core-plans/issues/2698, can this be closed also?

**Comment by smacfarlane** [comment] 2019-06-19 21:32
I may have spoken hastily on the other issue, my understanding was that it was caused by and issue with JobSrv that has been corrected. 

If you're able to run the command successfully now, I believe it's safe to close this out. If not, we need to do some additional investigation :smile:

**Comment by eeyun** [comment] 2019-06-25 15:30
This should have been resolved by the backend changes last week. Closing this for now, feel free to reopen if you hit this again!

**Closed by eeyun** 2019-06-25 15:30 UTC
Labels: C-bug
