### ISSUE TITLE
Unable to export private package to Docker image

### ISSUE THREAD

**Issue by emachnic** [habitat-sh/builder#353] opened 2018-03-29 18:27 UTC
I have a private Habitat package that I've built and promoted to the stable channel. I'm able to `hab pkg install` it but when I try to export to a Docker image, it says "Package not found". I have exported the correct HAB_AUTH_TOKEN and the origin but no dice.

**Comment by mwrock** [comment] 2018-04-02 22:55
Yes I have seen this too with private packages. This certainly seems like a bug to me. However a workaround would be to use the path to the hart file as the target of the export instead of the `origin/package` identifier. That should work for you.

**Comment by mwrock** [comment] 2018-04-07 00:31
Just checked and it does look like the latest master does not fix this.

**Comment by fnichol** [comment] 2018-04-09 18:12
I'm pretty sure this is a 2-part fix (feature?):

* We need an additional option of `--token` to the exporters (this is an oversight for sure)
* We need to update the `builder-worker` component to pass a token to the exporter when invoking them

**Comment by eeyun** [comment] 2018-06-14 19:22
The first PR to correct this is up here:
It adds the --auth flag to the exporter the value of which gets piped through to the install function. We were literally passing `None` to the auth flag for the install of the user's packages.
https://github.com/habitat-sh/habitat/pull/5203

**Comment by eeyun** [comment] 2018-06-14 19:22
I'm going to validate the build worker momentarily.

**Comment by eeyun** [comment] 2018-06-15 16:53
Looking at builder, i don't think this same error occurs but i'm not certain how thats the case. I validated docker exporting for a private package from my own origin and could not reproduce that case. That being said when that PR is merged we can probably consider this closed.

**Comment by irvingpop** [comment] 2018-07-21 17:45
I can reproduce this with a private build.

**Comment by eeyun** [comment] 2018-07-22 18:51
Hmm this wasn't reproducable with private builds in builder at the time this was reported - it could be the same issue or it could even be somewhat related - can you provide repro steps and logs @irvingpop ?

**Comment by fnichol** [comment] 2018-08-10 19:19
:cake:

**Comment by irvingpop** [comment] 2018-08-11 20:55
Are there any settings I need to change to pick this up?   I just re-tested a build and encountered the same error, I'm guessing that builders haven't been updated with this fix yet

**Comment by eeyun** [comment] 2018-08-13 13:59
No you shouldn't need to do anything. It should just work :tm: once the new workers get released!

**Comment by irvingpop** [comment] 2018-08-13 15:25
Thanks, could you please send me a ping when that happens?

**Comment by xacaxulu** [comment] 2019-07-18 07:48
+1
adding ' --auth $HAB_AUTH_TOKEN' worked for me

**Closed** 2019-08-13 16:01 UTC
Labels: A-builder, A-exporter, C-bug, C-feature, E-less-easy, I-linux, I-windows, L-rust, V-devx
