### ISSUE TITLE
on-prem builder not pulling down all packages needed

### ISSUE THREAD

**Issue by lfillmore** [habitat-sh/builder#628] opened 2018-09-11 16:28 UTC
I have tried on multiple occasions but it seems the on prem builder missing packages.
the newest version of core/yarn is out with support for 10.9 but the on prem builder won't pull it down no matter how many times I do a search or try to install it.

I also notice that nodejs on the on prem builder skipped version 10.8 and went and grabbed 10.9.

The problem is that the version of yarn that the on prem builder pulled only wanted 10.8. The builder should just pull and not skip versions. Honestly we should be able to set an automatic interval to pull down all available packages and to lock our builder box as well. The biggest thing is to pull down when asked for it.

**Comment by elliott-davis** [comment] 2018-09-18 17:45
Closing as a duplicate of: https://github.com/habitat-sh/builder/issues/500

**Closed by elliott-davis** 2018-09-18 17:45 UTC
