### ISSUE TITLE
Inconsistent package target and channel behavior on some packages

### ISSUE THREAD

**Issue by scotthain** [habitat-sh/builder#1112] opened 2019-07-02 22:19 UTC
### `hab` CLI version
[Version of the habitat binary where you are encountering the issue]

### Platform Details
Chrome browser

### Scenario:
Inconsistent UI behavior with certain packages

### Steps to Reproduce:
- go to https://bldr.habitat.sh/#/pkgs/chef/scaffolding-chef-infra
- drop down version `0.6.0`
issue 1 - `unstable` and other channels show up twice on some packages
- while on the same page do a hard refresh (cmd-shift-r on mac with chrome)
- drop down version `0.6.0`
issue 2 - the package target icon will change from the Linux icon to the Linux2 (or the other way) randomly for some packages

### Expected Result:
[What are you expecting to happen as the consequence of above reproduction steps?]

### Actual Result:
[What actually happens after the reproduction steps? Include the error output or a link to a gist if possible.]

**Comment by chefsalim** [comment] 2019-07-03 16:48
This is a duplicate of an issue we already have logged to properly account for multiple targets (especially with same revision) in the UI.  There is both a UI and a backend component to this.  When we return the package information, the backend returns the same entry multiple times.  However, the UI also does not recognize the multiple platforms within either of the query, so it will change the rendering based only on what platform was first in the response.  Example of response returned is below:

```
{
  "range_start": 0,
  "range_end": 22,
  "total_count": 23,
  "data": [
    {
      "origin": "chef",
      "name": "scaffolding-chef-infra",
      "version": "0.6.0",
      "release": "20190703155710",
      "channels": [
        "chef-effortless-master-habitat-build",
        "unstable"
      ],
      "platforms": [
        "x86_64-linux-kernel2"
      ]
    },
    {
      "origin": "chef",
      "name": "scaffolding-chef-infra",
      "version": "0.6.0",
      "release": "20190703155610",
      "channels": [
        "unstable",
        "chef-effortless-master-habitat-build"
      ],
      "platforms": [
        "x86_64-windows"
      ]
    },
    {
      "origin": "chef",
      "name": "scaffolding-chef-infra",
      "version": "0.6.0",
      "release": "20190703155555",
      "channels": [
        "unstable",
        "chef-effortless-master-habitat-build"
      ],
      "platforms": [
        "x86_64-linux"
      ]
    },
    {
      "origin": "chef",
      "name": "scaffolding-chef-infra",
      "version": "0.6.0",
      "release": "20190703153046",
      "channels": [
        "unstable",
        "chef-effortless-master-habitat-build"
      ],
      "platforms": [
        "x86_64-windows"
      ]
    },
    {
      "origin": "chef",
      "name": "scaffolding-chef-infra",
      "version": "0.6.0",
      "release": "20190703151829",
      "channels": [
        "unstable",
        "chef-effortless-master-habitat-build"
      ],
      "platforms": [
        "x86_64-linux"
      ]
    },
    {
      "origin": "chef",
      "name": "scaffolding-chef-infra",
      "version": "0.6.0",
      "release": "20190703151818",
      "channels": [
        "unstable",
        "chef-effortless-master-habitat-build"
      ],
      "platforms": [
        "x86_64-linux-kernel2"
      ]
    },
    {
      "origin": "chef",
      "name": "scaffolding-chef-infra",
      "version": "0.6.0",
      "release": "20190702202820",
      "channels": [
        "unstable",
        "chef-effortless-master-habitat-build"
      ],
      "platforms": [
        "x86_64-windows"
      ]
    },
    {
      "origin": "chef",
      "name": "scaffolding-chef-infra",
      "version": "0.6.0",
      "release": "20190702202805",
      "channels": [
        "unstable",
        "chef-effortless-master-habitat-build",
        "stable",
        "unstable",
        "chef-effortless-master-habitat-build"
      ],
      "platforms": [
        "x86_64-linux",
        "x86_64-linux-kernel2"
      ]
    },
    {
      "origin": "chef",
      "name": "scaffolding-chef-infra",
      "version": "0.6.0",
      "release": "20190702202805",
      "channels": [
        "unstable",
        "chef-effortless-master-habitat-build",
        "stable",
        "unstable",
        "chef-effortless-master-habitat-build"
      ],
      "platforms": [
        "x86_64-linux",
        "x86_64-linux-kernel2"
      ]
    },
    {
      "origin": "chef",
      "name": "scaffolding-chef-infra",
      "version": "0.6.0",
      "release": "20190702202805",
      "channels": [
        "unstable",
        "chef-effortless-master-habitat-build",
        "stable",
        "unstable",
        "chef-effortless-master-habitat-build"
      ],
      "platforms": [
        "x86_64-linux",
        "x86_64-linux-kernel2"
      ]
    },
    {
      "origin": "chef",
      "name": "scaffolding-chef-infra",
      "version": "0.6.0",
      "release": "20190702202805",
      "channels": [
        "unstable",
        "chef-effortless-master-habitat-build",
        "stable",
        "unstable",
        "chef-effortless-master-habitat-build"
      ],
      "platforms": [
        "x86_64-linux",
        "x86_64-linux-kernel2"
      ]
    },
    {
      "origin": "chef",
      "name": "scaffolding-chef-infra",
      "version": "0.6.0",
      "release": "20190702201855",
      "channels": [
        "stable",
        "unstable",
        "chef-effortless-master-habitat-build"
      ],
      "platforms": [
        "x86_64-linux"
      ]
    },
    {
      "origin": "chef",
      "name": "scaffolding-chef-infra",
      "version": "0.6.0",
      "release": "20190702201854",
      "channels": [
        "unstable",
        "chef-effortless-master-habitat-build"
      ],
      "platforms": [
        "x86_64-linux-kernel2"
      ]
    },
    {
      "origin": "chef",
      "name": "scaffolding-chef-infra",
      "version": "0.6.0",
      "release": "20190702195155",
      "channels": [
        "unstable",
        "stable",
        "chef-effortless-master-habitat-build"
      ],
      "platforms": [
        "x86_64-linux"
      ]
    },
    {
      "origin": "chef",
      "name": "scaffolding-chef-infra",
      "version": "0.6.0",
      "release": "20190702195153",
      "channels": [
        "unstable",
        "chef-effortless-master-habitat-build"
      ],
      "platforms": [
        "x86_64-linux-kernel2"
      ]
    },
    {
      "origin": "chef",
      "name": "scaffolding-chef-infra",
      "version": "0.6.0",
      "release": "20190702185730",
      "channels": [
        "chef-effortless-master-habitat-build",
        "unstable"
      ],
      "platforms": [
        "x86_64-linux"
      ]
    },
    {
      "origin": "chef",
      "name": "scaffolding-chef-infra",
      "version": "0.6.0",
      "release": "20190702185725",
      "channels": [
        "chef-effortless-master-habitat-build",
        "unstable"
      ],
      "platforms": [
        "x86_64-linux-kernel2"
      ]
    },
    {
      "origin": "chef",
      "name": "scaffolding-chef-infra",
      "version": "0.6.0",
      "release": "20190702181410",
      "channels": [
        "unstable",
        "chef-effortless-master-habitat-build"
      ],
      "platforms": [
        "x86_64-linux"
      ]
    },
    {
      "origin": "chef",
      "name": "scaffolding-chef-infra",
      "version": "0.6.0",
      "release": "20190702181404",
      "channels": [
        "unstable",
        "chef-effortless-master-habitat-build"
      ],
      "platforms": [
        "x86_64-linux-kernel2"
      ]
    },
    {
      "origin": "chef",
      "name": "scaffolding-chef-infra",
      "version": "0.6.0",
      "release": "20190702174510",
      "channels": [
        "chef-effortless-master-habitat-build",
        "unstable"
      ],
      "platforms": [
        "x86_64-linux"
      ]
    },
    {
      "origin": "chef",
      "name": "scaffolding-chef-infra",
      "version": "0.6.0",
      "release": "20190702174504",
      "channels": [
        "unstable",
        "chef-effortless-master-habitat-build"
      ],
      "platforms": [
        "x86_64-linux-kernel2"
      ]
    },
    {
      "origin": "chef",
      "name": "scaffolding-chef-infra",
      "version": "0.6.0",
      "release": "20190702172659",
      "channels": [
        "chef-effortless-master-habitat-build",
        "unstable"
      ],
      "platforms": [
        "x86_64-linux"
      ]
    },
    {
      "origin": "chef",
      "name": "scaffolding-chef-infra",
      "version": "0.6.0",
      "release": "20190702172655",
      "channels": [
        "chef-effortless-master-habitat-build",
        "unstable"
      ],
      "platforms": [
        "x86_64-linux-kernel2"
      ]
    }
  ]
}
```

**Comment by chefsalim** [comment] 2019-07-03 16:50
Duplicate of https://github.com/habitat-sh/builder/issues/944

**Closed by chefsalim** 2019-07-03 16:50 UTC
Labels: C-bug, V-front-end

**Comment by scotthain** [comment] 2019-07-03 17:04
Thanks @chefsalim !!
