### ISSUE TITLE
Builder UI showing incorrect visibility icon for non-Linux packages

### ISSUE THREAD

**Issue by chefsalim** [habitat-sh/builder#824] opened 2018-12-05 23:01 UTC
For non-Linux packages (that don't have any associated projects), the Builder UI is showing incorrect visibility icon.  It shows private visibility even though the origin and packages are public.  For example, core/windows-service

**Comment by jsirex** [comment] 2019-02-07 11:30
JDYI: For linux there is same issue.

**Comment by dmccown** [comment] 2019-07-30 17:12
Duplicate of #1098

**Closed by dmccown** 2019-07-30 17:12 UTC
Labels: A-builder, C-bug, V-bldr, V-front-end
