### ISSUE TITLE
[builder-web] Handle 404s on package pages

### ISSUE THREAD

**Issue by christophermaier** [habitat-sh/builder#292] opened 2018-03-12 17:00 UTC
@cnunciato commented on [Thu Jun 15 2017](https://github.com/habitat-sh/habitat/issues/2612)

For known bad package URLs:

https://bldr.habitat.sh/#/pkgs/hahanodoesntexist/nonsensepkgetc/0.1.0
https://bldr.habitat.sh/#/pkgs/hahanodoesntexist/nonsensepkgetc/0.1.0/20170615150934

.. we should render a more appropriate "not found" view.

**Comment by chefsalim** [comment] 2018-08-27 21:01
Duplicate of #68

**Closed by chefsalim** 2018-08-27 21:01 UTC
Labels: A-habitat.sh, C-chore, E-easy, L-html-css, V-bldr
