### ISSUE TITLE
github triggered group build fails whereas ``hab bldr job start --group...`` does not

### ISSUE THREAD

**Issue by gavindidrichsen** [habitat-sh/builder#1255] opened 2019-12-04 11:33 UTC
### `hab` CLI version
```bash
(travis_ci_version_2) ➜  core-plans git:(pr/3138) ✗ hab --version
hab 0.90.6/20191112141558
(travis_ci_version_2) ➜  core-plans git:(pr/3138) ✗
```

### Platform Details
Linux OS only

### Scenario:
When a github PR merge triggers a build job, some of the dependent builds fail to be added; whereas a manual cli trigger (e.g., ``hab bldr job start --group core/curl...``) of the same produces a successful job list.

### Steps to Reproduce:
* Invoke the Builder endpoint that is triggered by a github merged core-plans PR.  For example, in this scenario https://github.com/habitat-sh/core-plans/pull/3144 merged core/curl.
* Obtain the job ID from the command line.  For example, ``hab bldr job status -o core`` returned for core/curl a job id of 1393517447227211776.
* Record the progress list of all core dependent builds.  For example ``hab bldr job status 1393517447227211776  -s | sort | grep "core/"`` produces the list below.  **NOTE**:
  - although core/git has been built, triggered by this core/curl merge
  - nevertheless the build list below doesn't include core/git which was found to be the cause of the core/composer **Failure**.

```bash
(travis_ci_version_2) ➜  core-plans git:(pr/3138) ✗ hab bldr job status 1392667020189237248   -s | sort | grep "core/"
2019-12-02T11:10:37.056868+00:00  1392667020189237248  Complete  core/curl  x86_64-linux
core/R                                  Success  1392668544129441792  core/R/3.5.0/20191202114042                           x86_64-linux
core/composer                           Failure  1392688187556962304                                                        x86_64-linux
core/crate                              Success  1392668554825146368  core/crate/1.1.2/20191202120844                       x86_64-linux
core/curl                               Success  1392667021814898688  core/curl/7.67.0/20191202111040                       x86_64-linux
core/dotnet-core                        Success  1392668546310561792  core/dotnet-core/2.2.3/20191202115312                 x86_64-linux
core/dotnet-core-sdk                    Success  1392668546092449792  core/dotnet-core-sdk/2.2.401/20191202115243           x86_64-linux
core/drupal                             Success  1392701029131714560  core/drupal/8.3.2/20191202121815                      x86_64-linux
core/drush                              Success  1392688187347238912  core/drush/8/20191202121514                           x86_64-linux
core/etcd                               Success  1392668545874337792  core/etcd/v3.3.10/20191202115142                      x86_64-linux
core/grafana                            Success  1392668545656225792  core/grafana/6.4.3/20191202115043                     x86_64-linux
core/jenkins                            Success  1392668545438113792  core/jenkins/2.190.2/20191202114912                   x86_64-linux
core/lastpass-cli                       Success  1392668545220001792  core/lastpass-cli/1.3.3/20191202114812                x86_64-linux
core/netdata                            Success  1392668545001889792  core/netdata/1.17.0/20191202114442                    x86_64-linux
core/percona-xtrabackup                 Success  1392668544783777792  core/percona-xtrabackup/2.4.9/20191202114413          x86_64-linux
core/php                                Success  1392668544574054400  core/php/7.3.10/20191202114242                        x86_64-linux
core/qemu                               Success  1392668544347553792  core/qemu/2.11.1/20191202114112                       x86_64-linux
core/scaffolding-node                   Success  1392668543869386752  core/scaffolding-node/0.6.14/20191202114012           x86_64-linux
core/sensu-agent                        Success  1392668543408005120  core/sensu-agent/2.0.0-beta.2-4/20191202113912        x86_64-linux
core/sensu-backend                      Success  1392668543181504512  core/sensu-backend/2.0.0-beta.2-4/20191202113842      x86_64-linux
core/shield-agent                       Success  1392668542963392512  core/shield-agent/0.10.8/20191202113612               x86_64-linux
core/tlog                               Success  1392668542745280512  core/tlog/6/20191202113512                            x86_64-linux
core/wordpress                          Success  1392688187137515520  core/wordpress/4.7.4/20191202121344                   x86_64-linux
```

* After the above github-triggered build has completed, then manually trigger the same build job from the CLI, get the build job id, and record the progress list.  For example after manually triggering the core/curl build with ``hab bldr job start --group core/curl x86_64-linux``, getting job ID of 1393522747787288576, and listing the builds as below with ``hab bldr job status 1393522747787288576  -s | sort | grep "core/"``.  Observe a couple things:
  - core/git is included
  - core/composer builds successfully this time.
  - core/img does not succeed and hasn't succeeded for several months.  An issue has been raised for this here https://github.com/habitat-sh/core-plans/issues/3151

```bash
2019-12-03T15:30:47.735780+00:00  1393522747787288576  Complete  core/curl  x86_64-linux
core/R                                  Success  1393524267751964672  core/R/3.5.0/20191203154652                            x86_64-linux
core/composer                           Success  1393536359477960704  core/composer/1.9.0/20191203163725                     x86_64-linux
core/crate                              Success  1393524276216381440  core/crate/1.1.2/20191203162224                        x86_64-linux
core/curl                               Success  1393522749699014656  core/curl/7.67.0/20191203153051                        x86_64-linux
core/dotnet-core                        Success  1393524267315740672  core/dotnet-core/2.2.3/20191203154151                  x86_64-linux
core/dotnet-core-sdk                    Success  1393524267106017280  core/dotnet-core-sdk/2.2.401/20191203154122            x86_64-linux
core/drupal                             Success  1393558025767788544  core/drupal/8.3.2/20191203164355                       x86_64-linux
core/drush                              Success  1393536359696072704  core/drush/8/20191203163755                            x86_64-linux
core/etcd                               Success  1393524267978465280  core/etcd/v3.3.10/20191203154722                       x86_64-linux
core/git                                Success  1393524264899731456  core/git/2.23.0/20191203153351                         x86_64-linux
core/github_changelog_generator         Success  1393526285690880000  core/github_changelog_generator/1.14.3/20191203163655  x86_64-linux
core/gocd-server                        Success  1393526284130541568  core/gocd-server/18.9.0/20191203163325                 x86_64-linux
core/grafana                            Success  1393524267533852672  core/grafana/6.4.3/20191203154421                      x86_64-linux
core/img                                Failure  1393526284583542784                                                         x86_64-linux
core/jenkins                            Success  1393524268204965888  core/jenkins/2.190.2/20191203154722                    x86_64-linux
core/lastpass-cli                       Success  1393524268867690496  core/lastpass-cli/1.3.3/20191203155052                 x86_64-linux
core/netdata                            Success  1393524269085802496  core/netdata/1.17.0/20191203155322                     x86_64-linux
core/opam                               Success  1393526283476205568  core/opam/1.2.2/20191203163055                         x86_64-linux
core/percona-xtrabackup                 Success  1393524265335955456  core/percona-xtrabackup/2.4.9/20191203153351           x86_64-linux
core/php                                Success  1393524268423077888  core/php/7.3.10/20191203154752                         x86_64-linux
core/qemu                               Success  1393524268649578496  core/qemu/2.11.1/20191203154852                        x86_64-linux
core/scaffolding-go                     Success  1393526283031592960  core/scaffolding-go/0.2.0/20191203162925               x86_64-linux
core/scaffolding-go17                   Success  1393526283249704960  core/scaffolding-go17/0.1.0/20191203163025             x86_64-linux
core/scaffolding-node                   Success  1393524269748527104  core/scaffolding-node/0.6.14/20191203155823            x86_64-linux
core/sensu-agent                        Success  1393524270193139712  core/sensu-agent/2.0.0-beta.2-4/20191203160123         x86_64-linux
core/sensu-backend                      Success  1393524270411251712  core/sensu-backend/2.0.0-beta.2-4/20191203160253       x86_64-linux
core/sentinel                           Success  1393526282805092352  core/sentinel/0.1.0/20191203162923                     x86_64-linux
core/shield-agent                       Success  1393524269530415104  core/shield-agent/0.10.8/20191203155822                x86_64-linux
core/tlog                               Success  1393524270847475712  core/tlog/6/20191203160523                             x86_64-linux
core/wordpress                          Success  1393536359922573312  core/wordpress/4.7.4/20191203163755                    x86_64-linux
```

### Expected Result:
Both jobs should have contained an equal list of dependent builds

### Actual Result:
The github triggered is missing dependencies that are causing build failures:
![image](https://user-images.githubusercontent.com/16652757/70138781-ea456080-1688-11ea-8e97-2c921e50b502.png)

**Comment by gavindidrichsen** [comment] 2019-12-04 14:49
Adding another scenario that I saw recently which I think is probably related:  After merging #3144 with plan.sh changes to both core/curl-static-musl and core/curl:

![image](https://user-images.githubusercontent.com/16652757/69955094-c9e49d00-14f4-11ea-8d4d-1b5decdad9ee.png)

Only the core/curl-static-musl appeared in the Builder status output, not core/curl as well:

<img width="489" alt="image" src="https://user-images.githubusercontent.com/16652757/69955182-f8fb0e80-14f4-11ea-8db2-7e3cf5a0060a.png">


Only by kicking off a manual build in Builder did the job start:

<img width="949" alt="image" src="https://user-images.githubusercontent.com/16652757/69955251-2ba50700-14f5-11ea-863e-7385272d8780.png">

```bash
(travis_ci_version_2) ➜  core-plans git:(pr/3142) ✗ hab bldr job status -o core
☁ Determining status of job groups in core origin

CREATED AT                        GROUP ID             STATUS       IDENT                  TARGET
2019-12-02T11:10:37.056868+00:00  1392667020189237248  Dispatching  core/curl              x86_64-linux
2019-12-02T11:00:45.103038+00:00  1392662054527557632  Complete     core/bind              x86_64-linux
2019-12-02T10:01:33.119443+00:00  1392632258326134784  Complete     core/curl-static-musl  x86_64-linux
```

**Comment by chefsalim** [comment] 2020-01-21 19:35
Thanks for the very detailed bug report @gavindidrichsen!
This looks like something we do need to investigate further.

**Comment by smacfarlane** [comment] 2020-02-05 21:14
I've done some initial research into this and this is what I've discovered so far.  

Github Push notification and `hab bldr job start` have different entry points into the system, but they both dispatch `(plan, target)` to jobsrv, which is where rdeps are added to the Job group.

Github Push notifications enter the system through [/notify](https://github.com/habitat-sh/builder/blob/master/components/builder-api/src/server/resources/notify.rs#L27) and then handled by [handle_push](https://github.com/habitat-sh/builder/blob/master/components/builder-api/src/server/services/github.rs#L153).  This uses the contents of the payload, combined with project settings and bldr.toml to determine what needs to be built, and then [dispatches the (plan,target) combinations to jobsrv](https://github.com/habitat-sh/builder/blob/master/components/builder-api/src/server/services/github.rs#L245-L260)

`hab bldr job start` enters the system through [/depot/pkgs/schedule/{origin}/{pkg}?{target}](https://github.com/habitat-sh/builder/blob/master/components/builder-api/src/server/resources/pkgs.rs#L144-L145), which is handled by [schedule_job_group](https://github.com/habitat-sh/builder/blob/master/components/builder-api/src/server/resources/pkgs.rs#L527). Since this operates only on a single plan+target, it only needs to [set up the request and dispatch to jobsrv](https://github.com/habitat-sh/builder/blob/master/components/builder-api/src/server/resources/pkgs.rs#L552-L575). One difference to note here, is that this api sets a few different values in the request to jobsrv, but `set_package_only` is the only one exposed to the cli, and the job as dispatched in this issue would have the same value as what we would expect from github (build all rdeps). 

The [JobGroupSpec](https://github.com/habitat-sh/builder/blob/master/components/builder-jobsrv/src/server/mod.rs#L101) message is handled by [job_group_create](https://github.com/habitat-sh/builder/blob/master/components/builder-jobsrv/src/server/handlers.rs#L306) in jobsrv. At this point, both methods of requesting a build job be started should be in the same code path, as this function starts by parsing a [JobGroupSpec](https://github.com/habitat-sh/builder/blob/master/components/builder-jobsrv/src/server/handlers.rs#L306) which only contains a single origin/pkg/target and options. This function does a bunch of set up work to determine if the thing requested is buildable, and if it is, [rdeps are added if requested](https://github.com/habitat-sh/builder/blob/master/components/builder-jobsrv/src/server/handlers.rs#L378). This would be an all-or-nothing operation, which is why I doubt that the option in the JobGroupSpec differed between the two requests.

Given these two code paths and where rdeps are added to the build group, I would expect the above examples to produce the same job groups, though they obviously did not.   

There are a few hypotheses as to what might have happened and some additional investigation we can do.

#### The payload we got from github is not what we think it is.

This is hard to verify given the age of these requests. I looked through our notification payloads in the Github UI, but the volume of traffic is so high that it took 5 minutes to go back half a day, and there's no way to request a point in time. 

I also suspect that this isn't the issue, as part of the prep work to dispatch to jobsrv is to load the Project settings. This would be the same between GHPush and `job start`, otherwise we'd see multiple `core/curl` projects configured of which there aren't. 

#### GHPush reuses the connection to dispatch multiple jobs

The [request](https://github.com/habitat-sh/builder/blob/master/components/builder-jobsrv/src/server/handlers.rs#L378) is created outside of the iteration over [plans](https://github.com/habitat-sh/builder/blob/master/components/builder-api/src/server/services/github.rs#L223) which means we're re-using the request for multiple dispatchs.  We are setting the same options on each dispatch though, and if `core/curl` was somehow getting mangled with `core/curl-static-musl`, I would have expected different behavior. This still does bear looking into though.

#### Packages can be excluded from the build, which in turn excludes all of their rdeps

This is also unlikely, given that the two builds would be pulling from the same sources, the database of configured projects, and the in memory representation of the graph. This does bear a closer look though, to ensure we don't have a subtle logic error.

#### The in-memory package graph changed between the two job dispatches

This one will be hard to debug, as the state of the graph has changed since this issue was filed and may not be reproducible. It is possible that this is the cause, if our cycle detection caused the edge between curl and git to be dropped, but the dependencies on those packages haven't changed in 4 years, with the exception of adding `core/sed` to git 14 months ago. 

### Next steps
We should attempt to reproduce this behavior, though I can't think of a good way other than introducing a whitespace change to mock the the original PR that was merged. 

It would also be nice to add some tooling to inspect the build graph as jobsrv sees it.  The `rdeps` api endpoint does provide a window into this, but some cli tooling to query/filter the information would be better. 

cc @chefsalim @markan

**Comment by smacfarlane** [comment] 2020-02-07 23:12
Thanks for this report and detailed write-up @gavindidrichsen.  

I was unable to reproduce this using a copy of live data and a simulated GitHub Push notification with the same changed files, commit shas, etc. from the linked PR.  This lead me to do some additional reading of how our package graph is generated and I believe what you encountered was #1302. 

I'm going to go ahead and close this one out in favor of #1302. If you encounter this again, please feel free to re-open this and we can do a closer inspection of the logs to determine if it is a separate issue from #1302 .

**Closed by smacfarlane** 2020-02-07 23:12 UTC
Labels: C-bug

**Comment by gavindidrichsen** [comment] 2020-02-24 12:44
Thanks @smacfarlane.
