### ISSUE TITLE
[builder-web] [Docker export] Binlinking ld fails with core/scaffolding-ruby

### ISSUE THREAD

**Issue by kevinreedy** [habitat-sh/builder#240] opened 2018-03-02 22:06 UTC
`kevinreedy/automate-hipchat-notifier` is failing to export to Docker on bldr web, but works fine in hab studio locally with hab 0.54.0/20180221020527. [This app's plan](https://github.com/kevinreedy/automate-hipchat-notifier/blob/master/habitat/plan.sh) is just using scaffolding-ruby. 

Output from the build:
```
★ Install of kevinreedy/automate-hipchat-notifier/0.1.0/20180302213135 complete with 16 new packages installed.
✓ Changing permissions on "/tmp/hab-pkg-export-docker.WZ0glpHYHur5/rootfs/hab"

...

» Binlinking ld from kevinreedy/automate-hipchat-notifier/0.1.0/20180302213135 into /tmp/hab-pkg-export-docker.WZ0glpHYHur5/rootfs/bin
✗✗✗
✗✗✗ `ld' was not found under any 'PATH' directories in the kevinreedy/automate-hipchat-notifier/0.1.0/20180302213135 package
✗✗✗
builder_log_section::end::export_docker
builder_log::end::929122949661646848
```

**Comment by chefsalim** [comment] 2018-03-02 23:24
Possible regression with new stable versions of core/docker and core/hab-pkg-export-docker packages?

**Comment by elliott-davis** [comment] 2018-03-07 22:46
So this seems to be a side effect of over aggressive binlinking after we changed the `PATH` metadata file to mirror the `RUNTIME_ENVIRONMENT`. The reason this is hitting this particular plan is because the ruby scaffolding depends on binutils as a transitive dep so we end up with a conflicting link.

@fnichol @christophermaier does that sound right?

**Comment by fnichol** [comment] 2018-03-08 19:45
So some updates here…

There is a root cause to this which isn't related to Builder, or the exporter, but rather how our code is currently interpreting the `PATH` metadata file in a package made today--and it's current contents.

We found out yesterday that the contents of the `PATH` metadata file have contained more than just the paths to binaries for that package, but rather all other `$PATH` entries required for the software in that package to run.

For example, given a package `core/foo` that has a `pkg_bin_dirs=(bin sbin)` in its `plan.sh`, we would normally expect to find something like this in the `PATH` metadata file:

```
/hab/pkgs/core/foo/0.1.0/20180302213135/bin:/hab/pkgs/core/foo/0.1.0/20180302213135/sbin
```

However instead, we're seeing something like this:

```
/hab/pkgs/core/foo/0.1.0/20180302213135/bin:/hab/pkgs/core/foo/0.1.0/20180302213135/sbin:/hab/pkgs/core/coreutils/8.29/20180306011915/bin:/hab/pkgs/core/libcap/2.25/20180306005510/bin:/hab/pkgs/core/attr/2.4.47/20180306004834/bin:/hab/pkgs/core/glibc/2.26/20180302223514/bin:/hab/pkgs/core/acl/2.2.52/20180306005031/bin
```
where the other packages would have been direct run dependencies containing `pkg_bin_dirs` entries themselves.

Typically the value of this `PATH` metadata file gets used in the following places (not exhaustive, potentially not 100% accurate):

* Our binlinking logic which searches for a command or when iterating over all paths to symlink all binaries
* Our `pkg provides` logic which searches through packages looking for a command in a package
* Our Supervisor in a fallback mode when a `RUNTIME_ENVIRONMENT` package metadata file doesn't exist
* Our code `PkgInstall#paths()` method, also when a `RUNTIME_ENVIRONMENT` package metadata file doesn't exist
* Possibly other places?

## Updated Interpretation

After chatting about this with @elliott-davis and @christophermaier we came to the realization that there still is a function for the `PATH` metadata file which is to communicate: "these path entries have command binaries in them and these path entries are all local to my package". This is distinctly different than "I need all of these path entries on `$PATH` in order for my program binaries to work"--which is the function of the `PATH` entry in the `RUNTIME_ENVIRONMENT` metadata file. 

## Fixes

To make the above realizations a current reality, a few updates will be required (again, possibly not exhaustive):

* Update the build program in `habitat-sh/habitat` to write `PATH` as it previously done (see above).
* Update the `PkgInstall#paths()` implementation to filter path entries that are not local to a package when parsing `PATH`.
* Ensure that the `PATH` metadata files are informing the build `$PATH` that gets exported when the build program runs
* Confirm that these fixes resolve the Binlink/all code bugs
* Confirm nothing crazy is broken

I'll link issues as they relate here and leave this as the tracking issue.

**Comment by christophermaier** [comment] 2018-03-12 14:46
@fnichol possibly related: https://github.com/habitat-sh/habitat/issues/4669

**Comment by christophermaier** [comment] 2018-03-12 14:47
@fnichol also: https://github.com/habitat-sh/habitat/issues/4390

**Comment by jeremymv2** [comment] 2018-04-10 15:29
@fnichol I just wanted to point out that we are also seeing this in a NON scaffolding ruby project:  https://bldr.habitat.sh/#/pkgs/chef-server/oc_erchef/builds/956738929334550528 🤔

**Comment by christophermaier** [comment] 2018-04-10 15:37
@jeremymv2 it's independent of scaffolding... the description of the root cause (and fix) are in https://github.com/habitat-sh/core/pull/19. That should get merged in today.

**Comment by fnichol** [comment] 2018-04-13 07:28
@irvingpop @jeremymv2 @kevinreedy @jtimberman Okay, we're at the stage where it would be good to try out your builds in production. I've promoted a worker which should contain all the relevant work which I'm going to try and link here…

Closed by:

* habitat-sh/builder#338
* habitat-sh/builder#356
* habitat-sh/builder#367
* habitat-sh/habitat#4864
* habitat-sh/habitat#4875
* habitat-sh/habitat#4888
* habitat-sh/habitat#4895
* habitat-sh/habitat#4722
* habitat-sh/core#19
* habitat-sh/core#20
* habitat-sh/core#21
* habitat-sh/core#22

**Closed by fnichol** 2018-04-13 07:28 UTC
Labels: C-bug, T-stability

**Comment by qhartman** [comment] 2018-04-25 16:51
I'm seeing this behavior today: https://forums.habitat.sh/t/binlinking-step-failing-during-docker-export/506/3
